spring:
  # postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/your_postgresql_db
    username: your_postgresql_username
    password: your_postgresql_password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  # mongodb
  data:
    mongodb:
      host: localhost
      port: 27017
      database: your_mongodb_db
